name: Test

on:
  push:
    branches:
      - main
      - v2
      - rc1
      - rc2
  pull_request:

jobs:
  build:
    name: Jest Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: |
          export PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}
          export PRIVATE_KEY_SEPOLIA=${{ secrets.PRIVATE_KEY_SEPOLIA }}
          export PROVIDER_URI=${{ secrets.PROVIDER_URI }}
          export PROVIDER_URI_GOERLI=${{ secrets.PROVIDER_URI_GOERLI }}
          export PROVIDER_URI_SEPOLIA=${{ secrets.PROVIDER_URI_SEPOLIA }}
          npm test test/unit
