name: Test

on:
  push:
    branches:
      - main
      - v2
      - rc1
      - rc2
  pull_request:

jobs:
  build:
    name: Jest Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: |
          export PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}
          export PROVIDER_URI=${{ secrets.PROVIDER_URI }}
          export PROVIDER_URI_GOERLI=${{ secrets.PROVIDER_URI_GOERLI }}
          export PROVIDER_URI_SEPOLIA=${{ secrets.PROVIDER_URI_SEPOLIA }}
          ANVIL_PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
          export PRIVATE_KEY=$ANVIL_PRIVATE_KEY # just needs to be in the correct format, no tx is sent in unit tests
          export PRIVATE_KEY_GOERLI=$ANVIL_PRIVATE_KEY
          export PRIVATE_KEY_SEPOLIA=$ANVIL_PRIVATE_KEY
          npm test test/unit
